### ISSUE TITLE
Resolving dependencies

### ISSUE THREAD

**Issue by XJ653** [zhujian1989/ZhihuDailyPurifyByFlutter#2]
一直在Resolving dependencies，过一阵子之后会报错
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: H:\Flutter\ZhihuDailyPurifyByFlutter\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_webview_plugin'.
> Could not resolve all files for configuration ':flutter_webview_plugin:classpath'.
   > Could not download lint-checks.jar (com.android.tools.lint:lint-checks:25.3.0)
      > Could not get resource 'https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.3.0/lint-checks-25.3.0.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.3.0/lint-checks-25.3.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/143.204.132.159, d29vzk4ow07wi7.cloudfront.net/143.204.132.53, d29vzk4ow07wi7.cloudfront.net/143.204.132.57, d29vzk4ow07wi7.cloudfront.net/143.204.132.100] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 18s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by zhujian1989** [comment]
看起来是没拉下来这个包啊flutter_webview_plugi

**Comment by moonljt521** [comment]
我遇到了类似的问题，修改了gradle版本解决的，不知道能否帮到你。
用的gradle 版本4.6，插件版本为3.1.2的组合
