### ISSUE TITLE
执行packages get 失败

### ISSUE THREAD

**Issue by PeterXiaoWang** [zhujian1989/ZhihuDailyPurifyByFlutter#4]
Running "flutter packages get" in ZhihuDailyPurifyByFlutter...     
Because flutter_html_view <0.5.5 depends on cached_network_image ^0.4.0 and daily_purify depends on cached_network_image ^0.5.0, flutter_html_view <0.5.5 is forbidden.
So, because daily_purify depends on flutter_html_view ^0.3.1, version solving failed.

pub get failed (1)

**Comment by PeterXiaoWang** [comment]
降低cached_network_image为cached_network_image: ^0.4.0解决

**Comment by manburenshenglu** [comment]
这个是什么原因造成的，依赖版本号不一致吗？
